apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-cicd-demo
  template:
    metadata:
      labels:
        app: java-cicd-demo
    spec:
      containers:
        - name: java-cicd-demo
          image: priya123456/restapi:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-cicd-demo-service
spec:
  selector:
    app: java-cicd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
